# Generated by Django 3.2.20 on 2023-10-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_table',
            name='created',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
